audio_settings:
  enabled: false
  file_path: ''
  mode: tts
  startup_phrase: Good morning, Boss. Initializing systems.
  success_phrase: Systems online. Have a productive day.
clap_settings:
  filter_high: 1800
  filter_low: 1400
  frame_duration: 0.02
  min_interval: 0.2
  order: 2
  sampling_rate: 44100
  threshold: 0.15
logging:
  file: launcher.log
  level: INFO
system:
  active_routine: morning_routine
  first_run_completed: false
  last_control_center_version: '2'
  run_on_startup: null
  startup_delay: 0.0
routines:
  morning_routine:
    items:
    - enabled: true
      delay: 0
      monitor: primary
      name: HLN News
      position: full
      target: https://www.hln.be/
      type: url
    - enabled: true
      delay: 2
      monitor: 1
      name: Discord
      position: full
      target: discord
      type: app
    - enabled: true
      delay: 1
      monitor: 1
      name: Spotify
      position: full
      target: spotify
      type: app
